### ISSUE TITLE
Code example in README.rst is outdated

### ISSUE THREAD

**Issue by tuelwer** [dynamicslab/pysensors#10]
While [reviewing](https://github.com/openjournals/joss-reviews/issues/2828) your toolbox for JOSS I found out that the reconstruction example in the [README.rst](https://github.com/dynamicslab/pysensors/blob/master/README.rst) is outdated:

```text
>>> model = pysensors.Sensorselector(n_sensors=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pysensors' has no attribute 'Sensorselector'
```

I think `pysensors.Sensorselector` has been renamed to `pysensors.reconstruction.SSPOR()`.

**Comment by briandesilva** [comment]
Thanks for pointing this out! You're exactly right—we renamed `SensorSelector` in the code, but missed it here. I just pushed a fix.

**Comment by tuelwer** [comment]
I still have trouble running the code of the reconstruction example. For example `data` is never used and `method.selected_sensors` should probably be `model.get_selected_sensors()`. Please correct me if I'm wrong.

**Comment by briandesilva** [comment]
I'm terribly sorry—I should have looked more closely at the example. Everything should be fixed now. This time I've tested the commands to make sure they run properly. Please let me know if you have any more trouble.

Note that both `model.get_selected_sensors()` and `model.selected_sensors` are allowed (though `method` was incorrect).

**Comment by tuelwer** [comment]
Thanks! Seems to work now!
