### ISSUE TITLE
[Defect] In the case of cost_constrained_qr, the algorithm should error out if the number of sensors is larger than the number of samples

### ISSUE THREAD

**Issue by Jimmy-INL** [dynamicslab/pysensors#14]
In the cost_constrained_qr algorithms, there must be an assertion or an IOError if the number of sensors is greater than the number of samples, this will cause the current implementation after the sensors exceed the number of samples (i.e., after 300 in the notebook example) will start ignoring the constrained area.  Of course, this is a rare occasion, primarily since the whole idea is based on sparsity, but some users might have limited samples and might still try this.

To reproduce this issue, go to the `./examples/cost_constrained_qr.ipynb` and change `n_sensors` to 350, you will see sensors start to be placed in the constrained areas.

**Comment by briandesilva** [comment]
Thanks for pointing this out! I'll implement a fix and update the package in the next few weeks.

**Comment by briandesilva** [comment]
I've added a warning for this case and released it in v0.3.5.
