### ISSUE TITLE
Multi-dimensional SSPOR

### ISSUE THREAD

**Issue by LasseLedet** [dynamicslab/pysensors#16]
Awesome work you guys do in your research group🙌🙌🙌

I am looking into a case quite similar to what I have seen from your group - The von Karman example. 

Suppose I have the von Karman example of flow past a cylinder and wish to do SSPOR based on a minimal number of sensors. The challenge in my case is that I have an additional dimension to my data. Basically, I have the spatial-temporal snapshots for a bunch of different boundary conditions (or flow points if you like) and I am looking to find the best sensor placement to reconstruct the entire transient pressure field (for a given sensor input) and not just an instance. Can pySensor handle that?

Hope it makes sense

**Comment by briandesilva** [comment]
I think you should be able to concatenate all the snapshots together, treating each as a single example, and feed them to SSPOR to get a reasonable set of sensor locations. For any fixed time for which you have measurements at those sensor values, you can reconstruct the whole pressure field at that point in time. As far as I'm aware, PySensors is not capable of evolving the pressure field in time (i.e. constructing the pressure field at time t2 given measurements at time t1).

I'm going to close this issue, but feel free to reopen it if you'd like to discuss further.
